[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "22.12.0" }

[functions]
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"
  publish = "dist"
